### ISSUE TITLE
Possibility to configure API return keys

### ISSUE THREAD

**Issue by leroy0211** [mapado/rest-client-sdk#16]
`->findAll()` on the `AbstractClient` results in an empty array. 

I think this has to do with the `hydra:` prefix on the `member` key.
As far as I know the key for members on a collection is `members` instead of `hydra:member`

see: `convertList` method in the `AbstractClient` class.

**Comment by jdeniau** [comment]
The API we are using returns `hydra:members` instead of `members`. I think the two approach are possibles, and may vary depending on which output you choose. (or maybe it's a bug in my server implementation).

A quick (and a little dirty) solution may be to define in the configuration the key to access your collection members.

A quicker and dirtier solution is to test the `members` and the `hydra:members` key existance.

What do you think ?

**Comment by leroy0211** [comment]
Well, I think it is my bad. 
I just saw that the server of the api example I use, is over 2 years old. 

http://www.markus-lanthaler.com/hydra/api-demo/issues/

I think the `hydra:member` key _(and of course the `hydra:` prefix)_ is proposed somewhere between 2013 and today.

**Comment by jdeniau** [comment]
I think the two way are valid ways :

If you look at the [Json-ld playground](http://json-ld.org/playground/), you can see inline examples of the `context`. It defines a kind of namespace.

The thing with your server is that [the context](http://www.markus-lanthaler.com/hydra/api-demo/contexts/Collection.jsonld) override the `members` definition and refer directly to the hydra:members endpoint url.

**Comment by jdeniau** [comment]
Fixed in `0.20.0`, you  now have a "collectionKey" in the mapping that allows you to specify a custom key
