### ISSUE TITLE
Symfony 3.0

### ISSUE THREAD

**Issue by hvalcourtSerdy** [mapado/rest-client-sdk#39]
Hi, I would like to know if you plan to make a version of rest-client-sdk compatible with Symfony 3.0.

Thanks for the good work :-)

**Comment by jdeniau** [comment]
Hi, 

For now, our project using it is stuck on SF 2.x because of others dependencies, but as the rest-client-sdk is very lightly coupled with Symfony, it should already be compliant with SF 3. I think the only think "locking" it to 2.x is the composer.json file.

I pushed a branch with SF 3.0 compatibility.

Maybe you can help us there, can you try to do this. Try require the `sf3Compat` branch in your composer.json file:
```json
"mapado/rest-client-sdk-bundle": "dev-sf3Compat@dev",
```

This should work with a SF 3.x version.

Please let me know if it's OK or if you have any bugs, and I will bump a new tag if it's working.

Thank you !

**Comment by hvalcourtSerdy** [comment]
Hi,

it's working, thanks !!! :-)

N.B: only one little thing, the branch is based on a old version of the sdk, 0.14.2, and not 0.17

**Comment by jdeniau** [comment]
OK, I will publish everything this afternoon

**Comment by jdeniau** [comment]
The bundle is tagged as 0.18.0 and added Symfony 3.x.

Thank you for your report

**Comment by hvalcourtSerdy** [comment]
Merci beaucoup / thanks! :-)
